"""initial_oss — single-shot schema for the public release.

Squashes the 29 in-development migrations (which included tables for
now-removed Ports + Feedback modules and other churn) into one clean
initial migration autogenerated from the current `Base.metadata`.

Revision ID: 1ceb24911705
Revises:
Create Date: 2026-07-12

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ceb24911705'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_alert_rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('nl_description', sa.Text(), nullable=False),
    sa.Column('threshold_spec', sa.JSON(), nullable=False),
    sa.Column('check_script', sa.Text(), nullable=False),
    sa.Column('poll_interval_sec', sa.Integer(), nullable=False),
    sa.Column('cooldown_sec', sa.Integer(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('lark_chat_id', sa.String(length=200), nullable=True),
    sa.Column('lark_user_id', sa.String(length=200), nullable=True),
    sa.Column('escalate', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cwd', sa.String(length=1024), nullable=False),
    sa.Column('prompt_source', sa.String(length=2048), nullable=True),
    sa.Column('prompt_cached', sa.Text(), nullable=False),
    sa.Column('disable_skills', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_definition_name'), ['name'], unique=True)

    op.create_table('budget',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('scope_type', sa.Enum('GLOBAL', 'PROJECT', 'TASK', 'SOURCE', 'MODEL', 'SESSION', name='budgetscopetype', native_enum=False), nullable=False),
    sa.Column('scope_value', sa.String(length=512), nullable=True),
    sa.Column('period', sa.Enum('WINDOW_5H', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', name='budgetperiod', native_enum=False), nullable=False),
    sa.Column('token_limit', sa.Integer(), nullable=True),
    sa.Column('cost_limit', sa.Float(), nullable=True),
    sa.Column('warn_pct', sa.Float(), nullable=False),
    sa.Column('action', sa.Enum('WARN', 'BLOCK', name='budgetaction', native_enum=False), nullable=False),
    sa.Column('notify_channel', sa.JSON(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('last_state', sa.String(length=16), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_state',
    sa.Column('jsonl_path', sa.String(length=1024), nullable=False),
    sa.Column('last_offset', sa.BigInteger(), nullable=False),
    sa.Column('last_mtime', sa.Float(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('last_ctx_tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jsonl_path')
    )
    with op.batch_alter_table('file_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_state_session_id'), ['session_id'], unique=False)

    op.create_table('hit_observation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('reset_text', sa.String(length=200), nullable=True),
    sa.Column('msg_count_5h', sa.Integer(), nullable=False),
    sa.Column('cc_tokens_5h', sa.BigInteger(), nullable=False),
    sa.Column('cr_tokens_5h', sa.BigInteger(), nullable=False),
    sa.Column('input_tokens_5h', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens_5h', sa.BigInteger(), nullable=False),
    sa.Column('raw_session_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hit_observation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hit_observation_ts'), ['ts'], unique=False)

    op.create_table('hourly_rollup',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bucket_hour', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('project_path', sa.String(length=1024), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_creation_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('msg_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hourly_rollup', schema=None) as batch_op:
        batch_op.create_index('ix_hr_bucket', ['bucket_hour'], unique=False)
        batch_op.create_index('ix_hr_bucket_model_proj', ['bucket_hour', 'model', 'project_path'], unique=True)

    op.create_table('notification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('NEW_MESSAGE', 'AUTO_NEEDS_REVIEW', 'SESSION_CRASHED', 'AUTO_RUN_FAILED', 'TOKEN_WARNING', 'PORT_CONFLICT', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('channels_sent', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_session_id'), ['session_id'], unique=False)

    op.create_table('output',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.Enum('FILE', 'LOG', 'MARKDOWN', 'URL', 'JSON', name='outputtype', native_enum=False), nullable=False),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_output_run_id'), ['run_id'], unique=False)

    op.create_table('pricing_config',
    sa.Column('model_family', sa.String(length=50), nullable=False),
    sa.Column('input_per_million', sa.Float(), nullable=False),
    sa.Column('cache_creation_per_million', sa.Float(), nullable=False),
    sa.Column('cache_read_per_million', sa.Float(), nullable=False),
    sa.Column('output_per_million', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('model_family')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)

    op.create_table('raw_token_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('claude_session_id', sa.String(length=64), nullable=True),
    sa.Column('project_path', sa.String(length=1024), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_creation_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('is_subagent', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('command_type', sa.String(length=32), nullable=True),
    sa.Column('csm_session_id', sa.String(length=36), nullable=True),
    sa.Column('jsonl_offset', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_token_event', schema=None) as batch_op:
        batch_op.create_index('ix_rte_csm_session', ['csm_session_id'], unique=False)
        batch_op.create_index('ix_rte_session', ['claude_session_id'], unique=False)
        batch_op.create_index('ix_rte_source', ['source'], unique=False)
        batch_op.create_index('ix_rte_task_name', ['task_name'], unique=False)
        batch_op.create_index('ix_rte_ts', ['ts'], unique=False)
        batch_op.create_index('ux_rte_session_offset', ['claude_session_id', 'jsonl_offset'], unique=True, sqlite_where=sa.text('claude_session_id IS NOT NULL AND jsonl_offset IS NOT NULL'))

    op.create_table('schedule_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_def_id', sa.String(length=36), nullable=False),
    sa.Column('cron', sa.String(length=100), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_entry_workflow_def_id'), ['workflow_def_id'], unique=False)

    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('INTERACTIVE', 'AUTO', 'ONBOARDING_AGENT', 'SUPERVISOR_AGENT', 'CHAT_AGENT', name='sessiontype', native_enum=False), nullable=False),
    sa.Column('cwd', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('STARTING', 'RUNNING', 'IDLE', 'WAITING_INPUT', 'WAITING_AUTH', 'CRASHED', 'EXITED', 'ORPHANED', name='sessionstatus', native_enum=False), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('claude_session_id', sa.String(length=64), nullable=True),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('associated_run_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('last_activity_ts', sa.DateTime(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('ring_buffer_offset', sa.Integer(), nullable=False),
    sa.Column('current_tool', sa.String(length=200), nullable=True),
    sa.Column('last_assistant_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_associated_run_id'), ['associated_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_claude_session_id'), ['claude_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_superseded_by'), ['superseded_by'], unique=False)

    op.create_table('stage_execution',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('schedule_entry_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'NEEDS_REVIEW', name='runstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('mission_id', sa.String(length=36), nullable=True),
    sa.Column('stage_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_execution_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_execution_schedule_entry_id'), ['schedule_entry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_execution_session_id'), ['session_id'], unique=False)

    op.create_table('tool_invocation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('claude_session_id', sa.String(length=64), nullable=True),
    sa.Column('project_path', sa.String(length=1024), nullable=True),
    sa.Column('csm_session_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('command_type', sa.String(length=32), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_creation_tokens', sa.BigInteger(), nullable=False),
    sa.Column('cache_read_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_invocation', schema=None) as batch_op:
        batch_op.create_index('ix_ti_session', ['claude_session_id'], unique=False)
        batch_op.create_index('ix_ti_tool', ['tool_name'], unique=False)
        batch_op.create_index('ix_ti_ts', ['ts'], unique=False)

    op.create_table('usage_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('session_pct', sa.Integer(), nullable=True),
    sa.Column('session_reset', sa.String(length=200), nullable=True),
    sa.Column('week_pct', sa.Integer(), nullable=True),
    sa.Column('week_reset', sa.String(length=200), nullable=True),
    sa.Column('tier', sa.String(length=80), nullable=True),
    sa.Column('subscription_type', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=400), nullable=True),
    sa.Column('raw_pane', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_us_ts', ['ts'], unique=False)

    op.create_table('workflow_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('compiled_rules', sa.JSON(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'PASSED', 'REJECTED', 'ERROR', name='workflowreviewstatus', native_enum=False), nullable=False),
    sa.Column('review_report', sa.JSON(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_definition_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_definition_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_definition_project_id'), ['project_id'], unique=False)

    op.create_table('agent_conversation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_def_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_ts', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_def_id'], ['agent_definition.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_conversation_agent_def_id'), ['agent_def_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_conversation_session_id'), ['session_id'], unique=False)

    op.create_table('mission',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_def_id', sa.String(length=36), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('workspace_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'CANCELLED', 'SUCCEEDED', 'FAILED', name='missionstatus', native_enum=False), nullable=False),
    sa.Column('current_stage', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('audit_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_def_id'], ['workflow_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_workflow_def_id'), ['workflow_def_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_workflow_def_id'))
        batch_op.drop_index(batch_op.f('ix_mission_status'))

    op.drop_table('mission')
    with op.batch_alter_table('agent_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_conversation_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_conversation_agent_def_id'))

    op.drop_table('agent_conversation')
    with op.batch_alter_table('workflow_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_definition_project_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_definition_name'))
        batch_op.drop_index(batch_op.f('ix_workflow_definition_archived_at'))

    op.drop_table('workflow_definition')
    with op.batch_alter_table('usage_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_us_ts')

    op.drop_table('usage_snapshot')
    with op.batch_alter_table('tool_invocation', schema=None) as batch_op:
        batch_op.drop_index('ix_ti_ts')
        batch_op.drop_index('ix_ti_tool')
        batch_op.drop_index('ix_ti_session')

    op.drop_table('tool_invocation')
    with op.batch_alter_table('stage_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_execution_session_id'))
        batch_op.drop_index(batch_op.f('ix_stage_execution_schedule_entry_id'))
        batch_op.drop_index(batch_op.f('ix_stage_execution_mission_id'))

    op.drop_table('stage_execution')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_superseded_by'))
        batch_op.drop_index(batch_op.f('ix_session_claude_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_associated_run_id'))

    op.drop_table('session')
    with op.batch_alter_table('schedule_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_entry_workflow_def_id'))

    op.drop_table('schedule_entry')
    with op.batch_alter_table('raw_token_event', schema=None) as batch_op:
        batch_op.drop_index('ux_rte_session_offset', sqlite_where=sa.text('claude_session_id IS NOT NULL AND jsonl_offset IS NOT NULL'))
        batch_op.drop_index('ix_rte_ts')
        batch_op.drop_index('ix_rte_task_name')
        batch_op.drop_index('ix_rte_source')
        batch_op.drop_index('ix_rte_session')
        batch_op.drop_index('ix_rte_csm_session')

    op.drop_table('raw_token_event')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_archived_at'))

    op.drop_table('project')
    op.drop_table('pricing_config')
    with op.batch_alter_table('output', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_output_run_id'))

    op.drop_table('output')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_session_id'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('hourly_rollup', schema=None) as batch_op:
        batch_op.drop_index('ix_hr_bucket_model_proj')
        batch_op.drop_index('ix_hr_bucket')

    op.drop_table('hourly_rollup')
    with op.batch_alter_table('hit_observation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hit_observation_ts'))

    op.drop_table('hit_observation')
    with op.batch_alter_table('file_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_state_session_id'))

    op.drop_table('file_state')
    op.drop_table('budget')
    with op.batch_alter_table('agent_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_definition_name'))

    op.drop_table('agent_definition')
    op.drop_table('agent_alert_rule')
    # ### end Alembic commands ###
