"""Split-out from orchestrator.py: STATE.yaml serialization helpers.

Reads / writes the per-mission `<workspace>/STATE.yaml` snapshot that
external tools (post-mortem scripts, R9-R19 review agents, the live AUTO
claude reading prior-stage outputs) consume.

Kept as module-level async functions accepting the orchestrator instance
so this is a pure code move, not a class-splitting refactor. The
`WorkflowOrchestrator` retains a thin `_write_state_yaml` delegator that
forwards here — every existing caller (`await self._write_state_yaml(...)`,
`await orch._write_state_yaml(...)`) keeps working, and any
`monkeypatch.setattr(orch, "_write_state_yaml", spy)` in tests still
shadows the delegator via normal instance-attribute lookup.

Internal cross-calls that used to be `self._render_static_outputs(...)`
are rewritten to `orch._render_static_outputs(...)` — same semantics,
same monkeypatch-friendliness. The staticmethod stays on the class since
it's cheap and doesn't need moving.
"""
from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml
from sqlalchemy import select

from csm.models import (
    Mission,
    Output,
    Run,
    WorkflowDefinition,
)
from csm.modules.workflow.schema import load_workflow_spec

if TYPE_CHECKING:
    from csm.modules.workflow.orchestrator import WorkflowOrchestrator

log = logging.getLogger(__name__)

# Filename for the per-mission state snapshot written into the workspace.
# The live AUTO claude reads this file to find prior-stage outputs.
STATE_YAML_FILENAME = "STATE.yaml"
STATE_YAML_HEADER = "# auto-generated by CSM orchestrator — do not edit\n"


def _to_iso(dt: datetime | None) -> str | None:
    """Duplicated from orchestrator.py to avoid a circular import."""
    if dt is None:
        return None
    return dt.isoformat(timespec="seconds") + ("Z" if dt.tzinfo is None else "")


async def write_state_yaml(orch: WorkflowOrchestrator, mission_id: str) -> None:
    """Rewrite `<workspace>/STATE.yaml` from the live DB rows.

    Callers invoke this after every state-changing commit (launch,
    cancel, retry, stage advance, finalize, stage start). Writes
    are best-effort: if the workspace directory is missing or YAML
    serialization blows up we log and continue rather than rolling
    back the Mission transition the caller just committed.
    """
    try:
        snapshot, ws_path = await build_state_snapshot(orch, mission_id)
    except Exception:
        log.exception(
            "STATE.yaml snapshot build failed for mission %s", mission_id
        )
        return
    if snapshot is None or ws_path is None:
        return
    path = Path(ws_path) / STATE_YAML_FILENAME
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        body = yaml.safe_dump(
            snapshot, sort_keys=False, default_flow_style=False
        )
        path.write_text(STATE_YAML_HEADER + body, encoding="utf-8")
    except OSError:
        log.exception(
            "STATE.yaml write failed for mission %s at %s", mission_id, path
        )


async def build_state_snapshot(
    orch: WorkflowOrchestrator, mission_id: str
) -> tuple[dict[str, Any] | None, str | None]:
    """Read the live mission + every related Run row and shape the snapshot."""
    async with orch._sm() as db:
        mission = await db.get(Mission, mission_id)
        if mission is None:
            return None, None
        wf_row = await db.get(WorkflowDefinition, mission.workflow_def_id)
        if wf_row is None:
            return None, mission.workspace_path
        spec = load_workflow_spec(wf_row.yaml_content)

        runs_by_stage: dict[str, Run] = {}
        for row in (
            await db.execute(
                select(Run).where(Run.mission_id == mission_id)
            )
        ).scalars():
            if row.stage_name is None:
                continue
            # Keep the latest-started Run per stage (covers retry → new Run row).
            existing = runs_by_stage.get(row.stage_name)
            if existing is None or (
                row.started_at is not None
                and (existing.started_at is None or row.started_at >= existing.started_at)
            ):
                runs_by_stage[row.stage_name] = row

        outputs_by_run: dict[str, list[str]] = {}
        run_ids = [r.id for r in runs_by_stage.values()]
        if run_ids:
            for run_id, path in (
                await db.execute(
                    select(Output.run_id, Output.path)
                    .where(Output.run_id.in_(run_ids))
                    .order_by(Output.discovered_at)
                )
            ).all():
                outputs_by_run.setdefault(run_id, []).append(path)

    stages_snapshot: list[dict[str, Any]] = []
    for s in spec.stages:
        run = runs_by_stage.get(s.name)
        if run is None:
            stage_status = "pending"
            started = None
            finished = None
            outputs = orch._render_static_outputs(
                s.outputs or [],
                mission=mission,
                workflow_name=spec.name,
            )
        else:
            stage_status = (
                run.status.value if hasattr(run.status, "value") else str(run.status)
            )
            started = _to_iso(run.started_at)
            finished = _to_iso(run.ended_at)
            discovered = outputs_by_run.get(run.id, [])
            outputs = discovered if discovered else orch._render_static_outputs(
                s.outputs or [],
                mission=mission,
                workflow_name=spec.name,
            )
        stages_snapshot.append(
            {
                "name": s.name,
                "kind": s.kind,
                "status": stage_status,
                "started_at": started,
                "finished_at": finished,
                "outputs": outputs,
            }
        )

    snapshot: dict[str, Any] = {
        "mission_id": mission.id,
        "workflow_name": spec.name,
        "status": mission.status.value
        if hasattr(mission.status, "value")
        else str(mission.status),
        "params": dict(mission.parameters or {}),
        "started_at": _to_iso(mission.started_at),
        "ended_at": _to_iso(mission.ended_at),
        "current_stage": mission.current_stage,
        "workspace_path": mission.workspace_path,
        "stages": stages_snapshot,
    }
    if mission.failure_reason:
        snapshot["failure_reason"] = mission.failure_reason
    return snapshot, mission.workspace_path
